/*
 * GripPipeline.h
 *
 *  Created on: Feb 6, 2017
 *      Author: logan
 */
#pragma once

namespace grip {

/**
* A representation of the different types of blurs that can be used.
*
*/
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
/**
* GripPipeline class.
*
* An OpenCV pipeline generated by GRIP.
*/
class GripPipeline {
	private:
		cv::Mat blurOutput;
		cv::Mat rgbThresholdOutput;
		std::vector<std::vector<cv::Point> > findContoursOutput;
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void rgbThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void findContours(cv::Mat &, bool , std::vector<std::vector<cv::Point> > &);

	public:
		GripPipeline();
		void Process(cv::Mat& source0);
		cv::Mat* GetBlurOutput();
		cv::Mat* GetRgbThresholdOutput();
		std::vector<std::vector<cv::Point> >* GetFindContoursOutput();
};


} // end namespace grip

